/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example
import org.example.utilities.StringUtils
import org.apache.commons.text.WordUtils


import io.ktor.server.application.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*

fun main() {


    embeddedServer(Netty, port = 8080) {
        routing {
            get("/") {
                call.respondText("Hello, world!")
            }
        }
    }.start(wait = true)
}
