version: '3.8'

services:
  backend:
    build:
      context: ./server 
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  
    restart: always  

  frontend:
    build:
      context: ./client  
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  
    restart: always  
    depends_on:
      - backend 
    command: npm start 