services:
  backend:
    build:
      context: ./server 
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - TZ=Europe/Warsaw
  frontend:
    build:
      context: ./client 
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
